FROM ubuntu:18.04

ARG project_name

LABEL author="Andrey Levkin <alevkin@gmail.com>" \
  maintainer="Andrey Levkin <alevkin@gmail.com> \
              Some One <someone@mixbytes.io>" \
  version="0.1.0" \
  description="Base image for building Haya on Ubuntu"

COPY ./scripts /var/src/${project_name}/scripts

WORKDIR /var/src/${project_name}

RUN apt-get update && \
      apt-get install -y git curl sudo ccache && \
      cd scripts && \
      bash ${project_name}_build.sh -y -t && \
      rm -rf /var/src && rm -rf /var/cache && \
      rm -rf /var/lib/apt/lists/* && rm -rf /root/src
