Vagrant.configure("2") do |config|
  config.vm.box = "macinbox"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.linked_clone = true
    v.memory = 8096
    v.cpus = 8
  end
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew install python
  SHELL
end
